export interface Framework {
  value: string;
  label: string;
}

export interface Item {
  title: string;
  description: string;
  category: string;
  year: string;
  image: string;
}

export const frameworks: Framework[] = [
  { value: "", label: "All OTTs" },
  { value: "amazon-prime", label: "Amazon Prime" },
  { value: "netflix", label: "Netflix" },
  { value: "jiohotstar", label: "JioHotstar" },
  { value: "aha", label: "Aha" },
  { value: "sun-nxt", label: "Sun Nxt" },
  { value: "sony-liv", label: "Sony Liv" },
];

export const items2025: Item[] = [
  { title: "Thammudu", description: "Action Thriller film", category: "netflix", year: "Coming soon", image: "/images/Thammudu.jpeg" },
  { title: "Kuberaa", description: "Crime Thriller", category: "amazon-prime", year: "Coming soon", image: "/images/Kubera.jpg" },
  { title: "Bhairavam", description: "Thriller Action", category: "zee5", year: "18 Jul 2025", image: "/images/bhairavam.jpeg" },
  { title: "Narivetta", description: "thriller", category: "sony-liv", year: "11-07-2025", image: "/images/Narivetta.jpeg" },
  { title: "Mr.Rani", description: "comedy", category: "lionsgate-play", year: "11-07-2025", image: "/images/MR.RANI.jpeg" },
 { title: "8 Vasantalu", description: "Romance", category: "netflix", year: "11-07-2025", image: "/images/8Vasantalu .jpeg" },
  { title: "Sri Sri Sri Raajavaru", description: "Film", category: "aha", year: "04-07-2025", image: "/images/SriRaajavaru .jpeg" },
  { title: "Uppu Kappurambu", description: "Film", category: "amazon-prime", year: "04-07-2025", image: "/images/UppuKappurambu .jpeg" },
  { title: "Jagamerigina Satyam", description: "Film", category: "sun-nxt", year: "04-07-2025", image: "/images/JagameriginaSatyam .jpeg" },
  { title: "Usha Parinayam", description: "Film", category: "bms-stream", year: "04-07-2025", image: "/images/UshaParinayam .jpeg" },
  { title: "Thug Life (Telugu)", description: "Film", category: "netflix", year: "03-07-2025", image: "/images/ThugLife.jpg" },
  { title: "AIR", description: "Series", category: "etv-win", year: "03-07-2025", image: "/images/AIR.jpeg" },
  { title: "23 (Iravai Moodu)", description: "Film", category: "amazon-prime", year: "27-06-2025", image: "/images/23 (Iravai Moodu).jpeg" },
  { title: "Oka Pathakam Prakaaram", description: "Film", category: "sun-nxt", year: "27-06-2025", image: "/images/OkaPathakamPrakaaram .jpeg"},
  { title: "Saaree", description: "Film", category: "lionsgate-play", year: "27-06-2025", image: "/images/saaree.jpeg" },
  { title: "Viraatapalem", description: "Series", category: "zee5", year: "27-06-2025", image: "/images/viraatapalem.jpeg" },
  { title: "Oka Brundavanam", description: "Film", category: "etv-win", year: "20-06-2025", image: "/images/OkaBrundavanam .jpeg" },
  { title: "Ghatikachalam", description: "Film", category: "amazon-prime", year: "20-06-2025", image: "/images/Ghatikachalam.jpeg" },
  { title: "Alappuzha Gymkhana (Telugu)", description: "Film", category: "aha", year: "20-06-2025", image: "/images/AlappuzhaGymkhana.jpeg" },
  { title: "Kolla (Telugu)", description: "Film", category: "etv-win", year: "19-06-2025", image: "/images/Kolla.jpeg" },
  { title: "Haddhu Ledhu Raa", description: "Film", category: "amazon-prime", year: "19-06-2025", image: "/images/HaddhuLedhuRaa.jpeg" },
  { title: "Subham", description: "Film", category: "jiohotstar", year: "13-06-2025", image: "/images/Subham.jpeg" },
  { title: "Eleven (Telugu)", description: "Film", category: "amazon-prime", year: "13-06-2025", image: "/images/Eleven.jpeg" },
  { title: "Blind Spot", description: "Film", category: "amazon-prime", year: "13-06-2025", image: "/images/BlindSpot.jpeg" },
  { title: "DD Next Level (Telugu)", description: "Film", category: "zee5", year: "13-06-2025", image: "/images/DDNextLevel.jpeg" },
  { title: "Dear Uma", description: "Film", category: "sun-nxt", year: "13-06-2025", image: "/images/DearUma.jpeg" },
  { title: "Ace (Telugu)", description: "Film", category: "amazon-prime", year: "13-06-2025", image: "/images/Ace.jpeg" },
  { title: "Rana Naidu S2", description: "Series", category: "netflix", year: "13-06-2025", image: "/images/RanaNaiduS2 .jpeg" },
  { title: "Karthika Missing Case", description: "Film", category: "aha", year: "13-06-2025", image: "/images/KarthikaMissingCase .jpeg" },
  { title: "Dear Daddy", description: "Film", category: "etv-win", year: "08-06-2025", image: "/images/DearDaddy.jpeg" },
  { title: "Single", description: "Film", category: "amazon-prime", year: "06-06-2025", image: "/images/Single.jpeg" },
  { title: "Devika & Danny", description: "Series", category: "jiohotstar", year: "06-06-2025", image: "/images/Devika&Danny .jpeg" },
  { title: "Pelli Kani Prasad", description: "Film", category: "etv-win", year: "05-06-2025", image: "/images/PelliKaniPrasad .jpeg" },
  { title: "Jigel", description: "Film", category: "sun-nxt", year: "04-06-2025", image: "/images/Jigel.jpeg" },
  { title: "Tourist Family (Telugu)", description: "Film", category: "jiohotstar", year: "02-06-2025", image: "/images/TouristFamily.jpeg" },
  { title: "Retro (Telugu)", description: "Film", category: "netflix", year: "30-05-2025", image: "/images/Retro.jpeg" },
  { title: "Thudarum (Telugu)", description: "Film", category: "jiohotstar", year: "30-05-2025", image: "/images/Thudarum.jpeg" },
  { title: "HIT: The Third Case", description: "Film", category: "netflix", year: "29-05-2025", image: "/images/HIT.jpeg" },
  { title: "Chaurya Paatham", description: "Film", category: "amazon-prime", year: "27-05-2025", image: "https://placehold.co/100x100?text=Chaurya+Paatham" },
  { title: "Tantra", description: "Film", category: "amazon-prime", year: "24-05-2025", image: "https://placehold.co/100x100?text=Tantra" },
  { title: "Sarangapani Jathakam", description: "Film", category: "amazon-prime", year: "23-05-2025", image: "https://placehold.co/100x100?text=Sarangapani+Jathakam" },
  { title: "#Viral Prapancham", description: "Film", category: "sun-nxt", year: "23-05-2025", image: "https://placehold.co/100x100?text=%23Viral+Prapancham" },
  { title: "Pendulum (Telugu)", description: "Film", category: "etv-win", year: "22-05-2025", image: "https://placehold.co/100x100?text=Pendulum" },
  { title: "Bhavani Ward 1997", description: "Film", category: "amazon-prime", year: "20-05-2025", image: "https://placehold.co/100x100?text=Bhavani+Ward+1997" },
  { title: "Arjun Son Of Vyjayanthi", description: "Film", category: "amazon-prime", year: "16-05-2025", image: "https://placehold.co/100x100?text=Arjun+Son+Of+Vyjayanthi" },
  { title: "Amruthangamaya", description: "Film", category: "bms-stream", year: "16-05-2025", image: "https://placehold.co/100x100?text=Amruthangamaya" },
  { title: "Anaganaga", description: "Film", category: "etv-win", year: "15-05-2025", image: "https://placehold.co/100x100?text=Anaganaga" },
  { title: "Jolly O Gymkhana (Telugu)", description: "Film", category: "aha", year: "15-05-2025", image: "https://placehold.co/100x100?text=Jolly+O+Gymkhana" },
  { title: "Robinhood", description: "Film", category: "zee5", year: "10-05-2025", image: "https://placehold.co/100x100?text=Robinhood" },
  { title: "Karna Pisachi", description: "Film", category: "amazon-prime", year: "10-05-2025", image: "https://placehold.co/100x100?text=Karna+Pisachi" },
  { title: "Mercy Killing", description: "Film", category: "amazon-prime", year: "10-05-2025", image: "https://placehold.co/100x100?text=Mercy+Killing" },
  { title: "Kaalamega Karigindhi", description: "Film", category: "sun-nxt", year: "09-05-2025", image: "https://placehold.co/100x100?text=Kaalamega+Karigindhi" },
  { title: "Odela 2", description: "Film", category: "amazon-prime", year: "08-05-2025", image: "https://placehold.co/100x100?text=Odela+2" },
  { title: "Jack", description: "Film", category: "netflix", year: "08-05-2025", image: "https://placehold.co/100x100?text=Jack" },
  { title: "Good Bad Ugly (Telugu)", description: "Film", category: "netflix", year: "08-05-2025", image: "https://placehold.co/100x100?text=Good+Bad+Ugly" },
  { title: "Akkada Ammayi Ikkada Abbayi", description: "Film", category: "etv-win", year: "08-05-2025", image: "https://placehold.co/100x100?text=Akkada+Ammayi+Ikkada+Abbayi" },
  { title: "28 Degree Celsius", description: "Film", category: "amazon-prime", year: "29-04-2025", image: "https://placehold.co/100x100?text=28+Degree+Celsius" },
  { title: "MAD Square", description: "Film", category: "netflix", year: "25-04-2025", image: "https://placehold.co/100x100?text=MAD+Square" },
  { title: "Yaathisai (Telugu)", description: "Film", category: "aha", year: "25-04-2025", image: "https://placehold.co/100x100?text=Yaathisai" },
  { title: "Mazaka", description: "Film", category: "amazon-prime", year: "25-04-2025", image: "https://placehold.co/100x100?text=Mazaka" },
  { title: "Veera Dheera Soora", description: "Film", category: "amazon-prime", year: "24-04-2025", image: "https://placehold.co/100x100?text=Veera+Dheera+Soora" },
  { title: "L2: Empuraan (Telugu)", description: "Film", category: "jiohotstar", year: "24-04-2025", image: "https://placehold.co/100x100?text=L2+Empuraan" },
  { title: "Guardian", description: "Film", category: "aha", year: "24-04-2025", image: "https://placehold.co/100x100?text=Guardian" },
  { title: "Pranayam 1947", description: "Film", category: "aha", year: "24-04-2025", image: "https://placehold.co/100x100?text=Pranayam+1947" },
  { title: "Chhaava (Telugu)", description: "Film", category: "netflix", year: "12-04-2025", image: "https://placehold.co/100x100?text=Chhaava" },
  { title: "Court", description: "Film", category: "netflix", year: "11-04-2025", image: "https://placehold.co/100x100?text=Court" },
  { title: "Shanmukha", description: "Film", category: "aha", year: "11-04-2025", image: "https://placehold.co/100x100?text=Shanmukha" },
  { title: "Racharikam", description: "Film", category: "lionsgate-play", year: "11-04-2025", image: "https://placehold.co/100x100?text=Racharikam" },
  { title: "Tuk Tuk", description: "Film", category: "etv-win", year: "10-04-2025", image: "https://placehold.co/100x100?text=Tuk+Tuk" },
  { title: "Laxmi Kataksham", description: "Film", category: "aha", year: "04-04-2025", image: "https://placehold.co/100x100?text=Laxmi+Kataksham" },
  { title: "14 Days Girlfriend Intlo", description: "Film", category: "amazon-prime", year: "04-04-2025", image: "https://placehold.co/100x100?text=14+Days+Girlfriend+Intlo" },
  { title: "Hometown", description: "Series", category: "aha", year: "04-04-2025", image: "https://placehold.co/100x100?text=Hometown" },
  { title: "Inti Number 13", description: "Film", category: "amazon-prime", year: "04-04-2025", image: "https://placehold.co/100x100?text=Inti+Number+13" },
  { title: "Jaabilamma Neeku Antha Kopama", description: "Film", category: "amazon-prime", year: "31-03-2025", image: "https://placehold.co/100x100?text=Jaabilamma+Neeku+Antha+Kopama" },
  { title: "Madhushala", description: "Film", category: "etv-win", year: "31-03-2025", image: "https://placehold.co/100x100?text=Madhushala" },
  { title: "Mazaka", description: "Film", category: "zee5", year: "28-03-2025", image: "https://placehold.co/100x100?text=Mazaka" },
  { title: "Aghathiyaa (Telugu)", description: "Film", category: "sun-nxt", year: "28-03-2025", image: "https://placehold.co/100x100?text=Aghathiyaa" },
  { title: "Return of the Dragon", description: "Film", category: "netflix", year: "21-03-2025", image: "https://placehold.co/100x100?text=Return+of+the+Dragon" },
  { title: "Gandhi Tatha Chettu", description: "Film", category: "amazon-prime", year: "21-03-2025", image: "https://placehold.co/100x100?text=Gandhi+Tatha+Chettu" },
  { title: "Brahma Anandam", description: "Film", category: "aha", year: "20-03-2025", image: "https://placehold.co/100x100?text=Brahma+Anandam" },
  { title: "Officer On Duty (Telugu)", description: "Film", category: "netflix", year: "20-03-2025", image: "https://placehold.co/100x100?text=Officer+On+Duty" },
  { title: "Jithender Reddy", description: "Film", category: "etv-win", year: "20-03-2025", image: "https://placehold.co/100x100?text=Jithender+Reddy" },
  { title: "Rekhachithram (Telugu)", description: "Film", category: "aha", year: "14-03-2025", image: "https://placehold.co/100x100?text=Rekhachithram" },
  { title: "Ramam Raghavam", description: "Film", category: "etv-win", year: "14-03-2025", image: "https://placehold.co/100x100?text=Ramam+Raghavam" },
  { title: "Agent", description: "Film", category: "sony-liv", year: "14-03-2025", image: "https://placehold.co/100x100?text=Agent" },
  { title: "Hathya", description: "Film", category: "amazon-prime", year: "12-03-2025", image: "https://placehold.co/100x100?text=Hathya" },
  { title: "Laila", description: "Film", category: "amazon-prime", year: "09-03-2025", image: "https://placehold.co/100x100?text=Laila" },
  { title: "Thandel", description: "Film", category: "netflix", year: "07-03-2025", image: "https://placehold.co/100x100?text=Thandel" },
  { title: "Manamey", description: "Film", category: "amazon-prime", year: "07-03-2025", image: "https://placehold.co/100x100?text=Manamey" },
  { title: "Baapu", description: "Film", category: "jiohotstar", year: "07-03-2025", image: "https://placehold.co/100x100?text=Baapu" },
  { title: "Rewind", description: "Film", category: "lionsgate-play", year: "07-03-2025", image: "https://placehold.co/100x100?text=Rewind" },
  { title: "Pattudala", description: "Film", category: "netflix", year: "03-03-2025", image: "https://placehold.co/100x100?text=Pattudala" },
  { title: "Sankranthiki Vasthunam", description: "Film", category: "zee5", year: "01-03-2025", image: "https://placehold.co/100x100?text=Sankranthiki+Vasthunam" },
  { title: "Madraskaaran (Telugu)", description: "Film", category: "aha", year: "26-02-2025", image: "https://placehold.co/100x100?text=Madraskaaran" },
  { title: "Daaku Maharaaj", description: "Film", category: "netflix", year: "21-02-2025", image: "https://placehold.co/100x100?text=Daaku+Maharaaj" },
  { title: "Sammelanam", description: "Film", category: "etv-win", year: "21-02-2025", image: "https://placehold.co/100x100?text=Sammelanam" },
  { title: "Marco (Telugu)", description: "Film", category: "aha", year: "21-02-2025", image: "https://placehold.co/100x100?text=Marco" },
  { title: "Bhairathi Ranagal (Telugu)", description: "Film", category: "aha", year: "13-02-2025", image: "https://placehold.co/100x100?text=Bhairathi+Ranagal" },
  { title: "Kadhalikka Neramillai (Telugu)", description: "Film", category: "netflix", year: "11-02-2025", image: "https://placehold.co/100x100?text=Kadhalikka+Neramillai" },
  { title: "Game Changer", description: "Film", category: "amazon-prime", year: "07-02-2025", image: "https://placehold.co/100x100?text=Game+Changer" },
  { title: "Vivekanandan Viral", description: "Film", category: "aha", year: "07-02-2025", image: "https://placehold.co/100x100?text=Vivekanandan+Viral" },
  { title: "Kobali", description: "Series", category: "jiohotstar", year: "04-02-2025", image: "https://placehold.co/100x100?text=Kobali" },
  { title: "Dark", description: "Film", category: "amazon-prime", year: "03-02-2025", image: "https://placehold.co/100x100?text=Dark" },
  { title: "Identity (Telugu)", description: "Film", category: "zee5", year: "31-01-2025", image: "https://placehold.co/100x100?text=Identity" },
  { title: "Dhoom Dhaam", description: "Film", category: "amazon-prime", year: "31-01-2025", image: "https://placehold.co/100x100?text=Dhoom+Dhaam" },
  { title: "Coffee With A Killer", description: "Film", category: "aha", year: "31-01-2025", image: "https://placehold.co/100x100?text=Coffee+With+A+Killer" },
  { title: "Pushpa 2 The Rule", description: "Film", category: "netflix", year: "30-01-2025", image: "https://placehold.co/100x100?text=Pushpa+2+The+Rule" },
  { title: "Pothugadda", description: "Film", category: "etv-win", year: "30-01-2025", image: "https://placehold.co/100x100?text=Pothugadda" },
  { title: "Srikakulam Sherlockholmes", description: "Film", category: "etv-win", year: "24-01-2025", image: "https://placehold.co/100x100?text=Srikakulam+Sherlockholmes" },
  { title: "Razakar", description: "Film", category: "aha", year: "24-01-2025", image: "https://placehold.co/100x100?text=Razakar" },
  { title: "Sivarapalli", description: "Series", category: "amazon-prime", year: "24-01-2025", image: "https://placehold.co/100x100?text=Sivarapalli" },
  { title: "Fear", description: "Film", category: "amazon-prime", year: "23-01-2025", image: "https://placehold.co/100x100?text=Fear" },
  { title: "Wife Off", description: "Film", category: "etv-win", year: "23-01-2025", image: "https://placehold.co/100x100?text=Wife+Off" },
  { title: "Barroz (Telugu)", description: "Film", category: "disney-hotstar", year: "22-01-2025", image: "https://placehold.co/100x100?text=Barroz" },
  { title: "Vidudala Part 2", description: "Film", category: "amazon-prime", year: "19-01-2025", image: "https://placehold.co/100x100?text=Vidudala+Part+2" },
  { title: "Ramnagar Bunny", description: "Film", category: "aha", year: "17-01-2025", image: "https://placehold.co/100x100?text=Ramnagar+Bunny" },
  { title: "Mokshapatam", description: "Film", category: "aha", year: "14-01-2025", image: "https://placehold.co/100x100?text=Mokshapatam" },
  { title: "Sookshmadarshini (Telugu)", description: "Film", category: "disney-hotstar", year: "11-01-2025", image: "https://placehold.co/100x100?text=Sookshmadarshini" },
  { title: "Miss You", description: "Film", category: "amazon-prime", year: "10-01-2025", image: "https://placehold.co/100x100?text=Miss+You" },
  { title: "Bachhala Malli", description: "Film", category: "amazon-prime", year: "10-01-2025", image: "https://placehold.co/100x100?text=Bachhala+Malli" },
  { title: "Hide N Seek", description: "Film", category: "aha", year: "10-01-2025", image: "https://placehold.co/100x100?text=Hide+N+Seek" },
  { title: "Neeli Megha Shyama", description: "Film", category: "aha", year: "09-01-2025", image: "https://placehold.co/100x100?text=Neeli+Megha+Shyama" },
  { title: "Breakout", description: "Film", category: "etv-win", year: "09-01-2025", image: "https://placehold.co/100x100?text=Breakout" },
  { title: "Love Reddy", description: "Film", category: "aha", year: "03-01-2025", image: "https://placehold.co/100x100?text=Love+Reddy" },
  { title: "Katha Kamamishu", description: "Film", category: "aha", year: "02-01-2025", image: "https://placehold.co/100x100?text=Katha+Kamamishu" },
  { title: "Bloody Begger (Telugu)", description: "Film", category: "amazon-prime", year: "02-01-2025", image: "https://placehold.co/100x100?text=Bloody+Begger" },
  { title: "Movie M", description: "Adventure film", category: "amazon-prime", year: "22-09-2025", image: "/images/01.png" },
  { title: "Movie S", description: "Romantic drama", category: "amazon-prime", year: "07-07-2025", image: "https://placehold.co/100x100?text=Movie+S" },
];

export const items2024: Item[] = [
  { title: "Series B", description: "Crime drama series", category: "netflix", year: "15-03-2024", image: "https://placehold.co/100x100?text=Series+B" },
  { title: "Series H", description: "Fantasy epic", category: "netflix", year: "20-06-2024", image: "https://placehold.co/100x100?text=Series+H" },
  { title: "Series N", description: "Sci-fi series", category: "netflix", year: "10-09-2024", image: "https://placehold.co/100x100?text=Series+N" },
  { title: "Series T", description: "Documentary series", category: "netflix", year: "05-12-2024", image: "https://placehold.co/100x100?text=Series+T" },
  { title: "KCR (Keshava Chandra Ramavath)", description: "Film", category: "aha", year: "28-12-2024", image: "https://placehold.co/100x100?text=KCR" },
  { title: "RRR Behind And Beyond", description: "Documentary", category: "netflix", year: "27-12-2024", image: "https://placehold.co/100x100?text=RRR+Behind+And+Beyond" },
  { title: "Rahasyam Idam Jagath", description: "Film", category: "etv-win", year: "26-12-2024", image: "https://placehold.co/100x100?text=Rahasyam+Idam+Jagath" },
  { title: "Pottel", description: "Film", category: "amazon-prime", year: "20-12-2024", image: "https://placehold.co/100x100?text=Pottel" },
  { title: "Zebra", description: "Film", category: "aha", year: "20-12-2024", image: "https://placehold.co/100x100?text=Zebra" },
  { title: "Leela Vinodham", description: "Film", category: "etv-win", year: "19-12-2024", image: "https://placehold.co/100x100?text=Leela+Vinodham" },
  { title: "Mechanic Rocky", description: "Film", category: "amazon-prime", year: "13-12-2024", image: "https://placehold.co/100x100?text=Mechanic+Rocky" },
  { title: "Harikatha", description: "Series", category: "disney-hotstar", year: "13-12-2024", image: "https://placehold.co/100x100?text=Harikatha" },
  { title: "Roti Kapda Romance", description: "Film", category: "etv-win", year: "12-12-2024", image: "https://placehold.co/100x100?text=Roti+Kapda+Romance" },
  { title: "7/G – The Dark Story", description: "Film", category: "aha", year: "12-12-2024", image: "https://placehold.co/100x100?text=7%2FG+The+Dark+Story" },
  { title: "Thangalaan (Telugu)", description: "Film", category: "netflix", year: "10-12-2024", image: "https://placehold.co/100x100?text=Thangalaan" },
  { title: "Kanguva (Telugu)", description: "Film", category: "amazon-prime", year: "08-12-2024", image: "https://placehold.co/100x100?text=Kanguva" },
  { title: "Narudi Brathuku Natana", description: "Film", category: "amazon-prime", year: "06-12-2024", image: "https://placehold.co/100x100?text=Narudi+Brathuku+Natana" },
  { title: "Amaran (Telugu)", description: "Film", category: "netflix", year: "05-12-2024", image: "https://placehold.co/100x100?text=Amaran" },
  { title: "Mandira", description: "Film", category: "aha", year: "05-12-2024", image: "https://placehold.co/100x100?text=Mandira" },
  { title: "Matka", description: "Film", category: "amazon-prime", year: "05-12-2024", image: "https://placehold.co/100x100?text=Matka" },
  { title: "Naradan", description: "Film", category: "aha", year: "29-11-2024", image: "https://placehold.co/100x100?text=Naradan" },
  { title: "Thappinchuku  Sumathi", description: "Film", category: "aha", year: "28-11-2024", image: "https://placehold.co/100x100?text=Thappinchuku+Thiruguvadu+Dhanyudu+Sumathi" },
  { title: "Lucky Baskhar", description: "Film", category: "netflix", year: "28-11-2024", image: "https://placehold.co/100x100?text=Lucky+Baskhar" },
  { title: "KA", description: "Film", category: "etv-win", year: "28-11-2024", image: "https://placehold.co/100x100?text=KA" },
  { title: "Vikkatakavi", description: "Series", category: "zee5", year: "28-11-2024", image: "https://placehold.co/100x100?text=Vikkatakavi" },
  { title: "Sandeham", description: "Film", category: "etv-win", year: "28-11-2024", image: "https://placehold.co/100x100?text=Sandeham" },
  { title: "Appudo Ippudo Eppudo", description: "Film", category: "amazon-prime", year: "27-11-2024", image: "https://placehold.co/100x100?text=Appudo+Ippudo+Eppudo" },
  { title: "Laggam", description: "Film", category: "aha", year: "22-11-2024", image: "https://placehold.co/100x100?text=Laggam" },
  { title: "Bagheera (Telugu)", description: "Film", category: "netflix", year: "21-11-2024", image: "https://placehold.co/100x100?text=Bagheera" },
  { title: "I Hate Love", description: "Film", category: "etv-win", year: "21-11-2024", image: "https://placehold.co/100x100?text=I+Hate+Love" },
  { title: "Repati Velugu", description: "Film", category: "etv-win", year: "21-11-2024", image: "https://placehold.co/100x100?text=Repati+Velugu" },
  { title: "Martin (Telugu)", description: "Film", category: "amazon-prime", year: "19-11-2024", image: "https://placehold.co/100x100?text=Martin" },
  { title: "Maa Nanna Superhero", description: "Film", category: "zee5", year: "15-11-2024", image: "https://placehold.co/100x100?text=Maa+Nanna+Superhero" },
  { title: "Revu", description: "Film", category: "aha", year: "14-11-2024", image: "https://placehold.co/100x100?text=Revu" },
  { title: "Maa Nanna Super Hero", description: "Film", category: "amazon-prime", year: "13-11-2024", image: "https://placehold.co/100x100?text=Maa+Nanna+Super+Hero" },
  { title: "Devara", description: "Film", category: "netflix", year: "08-11-2024", image: "https://placehold.co/100x100?text=Devara" },
  { title: "ARM (Telugu)", description: "Film", category: "disney-hotstar", year: "08-11-2024", image: "https://placehold.co/100x100?text=ARM" },
  { title: "Janaka Aithe Ganaka", description: "Film", category: "aha", year: "08-11-2024", image: "https://placehold.co/100x100?text=Janaka+Aithe+Ganaka" },
  { title: "Vettaiyan (Telugu)", description: "Film", category: "amazon-prime", year: "08-11-2024", image: "https://placehold.co/100x100?text=Vettaiyan" },
  { title: "Operation Raavan", description: "Film", category: "aha", year: "02-11-2024", image: "https://placehold.co/100x100?text=Operation+Raavan" },
  { title: "Viswam", description: "Film", category: "amazon-prime", year: "01-11-2024", image: "https://placehold.co/100x100?text=Viswam" },
  { title: "CD (Criminal Or Devil)", description: "Film", category: "aha", year: "26-10-2024", image: "https://placehold.co/100x100?text=CD+Criminal+Or+Devil" },
  { title: "SWAG", description: "Film", category: "amazon-prime", year: "25-10-2024", image: "https://placehold.co/100x100?text=SWAG" },
  { title: "Sathyam Sundaram", description: "Film", category: "netflix", year: "25-10-2024", image: "https://placehold.co/100x100?text=Sathyam+Sundaram" },
  { title: "Little Hearts (Telugu)", description: "Film", category: "aha", year: "23-10-2024", image: "https://placehold.co/100x100?text=Little+Hearts" },
  { title: "Raid", description: "Film", category: "aha", year: "19-10-2024", image: "https://placehold.co/100x100?text=Raid" },
  { title: "Uruku Patela", description: "Film", category: "amazon-prime", year: "18-10-2024", image: "https://placehold.co/100x100?text=Uruku+Patela" },
  { title: "Love Sitara (Telugu)", description: "Film", category: "zee5", year: "18-10-2024", image: "https://placehold.co/100x100?text=Love+Sitara" },
  { title: "Yevam", description: "Film", category: "sun-nxt", year: "18-10-2024", image: "https://placehold.co/100x100?text=Yevam" },
  { title: "Kali", description: "Film", category: "etv-win", year: "17-10-2024", image: "https://placehold.co/100x100?text=Kali" },
  { title: "Mathu Vadalara 2", description: "Film", category: "netflix", year: "11-10-2024", image: "https://placehold.co/100x100?text=Mathu+Vadalara+2" },
  { title: "Utsavam", description: "Film", category: "amazon-prime", year: "11-10-2024", image: "https://placehold.co/100x100?text=Utsavam" },
  { title: "Sabari", description: "Film", category: "sun-nxt", year: "11-10-2024", image: "https://placehold.co/100x100?text=Sabari" },
  { title: "Gorre Puranam", description: "Film", category: "aha", year: "10-10-2024", image: "https://placehold.co/100x100?text=Gorre+Puranam" },
  { title: "Pailam Pilaga", description: "Film", category: "etv-win", year: "10-10-2024", image: "https://placehold.co/100x100?text=Pailam+Pilaga" },
  { title: "Balu Gani Talkies", description: "Film", category: "aha", year: "04-10-2024", image: "https://placehold.co/100x100?text=Balu+Gani+Talkies" },
  { title: "Kalinga", description: "Film", category: "aha", year: "04-10-2024", image: "https://placehold.co/100x100?text=Kalinga" },
  { title: "Bhale Unnade", description: "Film", category: "etv-win", year: "03-10-2024", image: "https://placehold.co/100x100?text=Bhale+Unnade" },
  { title: "35", description: "Film", category: "aha", year: "02-10-2024", image: "https://placehold.co/100x100?text=35" },
  { title: "Demonte Colony 2", description: "Film", category: "zee5", year: "27-09-2024", image: "https://placehold.co/100x100?text=Demonte+Colony+2" },
  { title: "Alanaati Ramachandrudu", description: "Film", category: "amazon-prime", year: "27-09-2024", image: "https://placehold.co/100x100?text=Alanaati+Ramachandrudu" },
  { title: "Prathinidi 2", description: "Film", category: "aha", year: "27-09-2024", image: "https://placehold.co/100x100?text=Prathinidi+2" },
  { title: "Saripodhaa Sanivaaram", description: "Film", category: "netflix", year: "26-09-2024", image: "https://placehold.co/100x100?text=Saripodhaa+Sanivaaram" },
  { title: "Chapra Murder Case", description: "Film", category: "aha", year: "26-09-2024", image: "https://placehold.co/100x100?text=Chapra+Murder+Case" },
  { title: "RTI", description: "Film", category: "etv-win", year: "26-09-2024", image: "https://placehold.co/100x100?text=RTI" },
  { title: "Kill (Telugu)", description: "Film", category: "disney-hotstar", year: "24-09-2024", image: "https://placehold.co/100x100?text=Kill" },
  { title: "Maruthi Nagar Subramanyam", description: "Film", category: "aha", year: "20-09-2024", image: "https://placehold.co/100x100?text=Maruthi+Nagar+Subramanyam" },
  { title: "Pekamedalu", description: "Film", category: "amazon-prime", year: "20-09-2024", image: "https://placehold.co/100x100?text=Pekamedalu" },
  { title: "Thiragabadara Saami", description: "Film", category: "aha", year: "19-09-2024", image: "https://placehold.co/100x100?text=Thiragabadara+Saami" },
  { title: "Suraapanam", description: "Film", category: "etv-win", year: "19-09-2024", image: "https://placehold.co/100x100?text=Suraapanam" },
  { title: "Sopathulu", description: "Film", category: "etv-win", year: "19-09-2024", image: "https://placehold.co/100x100?text=Sopathulu" },
  { title: "Parakramam", description: "Film", category: "aha", year: "14-09-2024", image: "https://placehold.co/100x100?text=Parakramam" },
  { title: "Aay", description: "Film", category: "netflix", year: "12-09-2024", image: "https://placehold.co/100x100?text=Aay" },
  { title: "Mr. Bachchan", description: "Film", category: "netflix", year: "12-09-2024", image: "https://placehold.co/100x100?text=Mr.+Bachchan" },
  { title: "Committee Kurrollu", description: "Film", category: "etv-win", year: "12-09-2024", image: "https://placehold.co/100x100?text=Committee+Kurrollu" },
  { title: "Aaha", description: "Film", category: "aha", year: "12-09-2024", image: "https://placehold.co/100x100?text=Aaha" },
  { title: "Satya", description: "Film", category: "aha", year: "07-09-2024", image: "https://placehold.co/100x100?text=Satya" },
  { title: "Nindha", description: "Film", category: "etv-win", year: "06-09-2024", image: "https://placehold.co/100x100?text=Nindha" },
  { title: "Simbaa", description: "Film", category: "aha", year: "06-09-2024", image: "https://placehold.co/100x100?text=Simbaa" },
  { title: "Double iSmart", description: "Film", category: "amazon-prime", year: "05-09-2024", image: "https://placehold.co/100x100?text=Double+iSmart" },
  { title: "Bhargavi Nilayam", description: "Film", category: "aha", year: "05-09-2024", image: "https://placehold.co/100x100?text=Bhargavi+Nilayam" },
  { title: "Sarangadhariya", description: "Film", category: "aha", year: "31-08-2024", image: "https://placehold.co/100x100?text=Sarangadhariya" },
  { title: "Shivam Bhaje", description: "Film", category: "amazon-prime", year: "30-08-2024", image: "https://placehold.co/100x100?text=Shivam+Bhaje" },
  { title: "Buddy", description: "Film", category: "netflix", year: "30-08-2024", image: "https://placehold.co/100x100?text=Buddy" },
  { title: "Honeymoon Express", description: "Film", category: "amazon-prime", year: "27-08-2024", image: "https://placehold.co/100x100?text=Honeymoon+Express" },
  { title: "Prabuthwa Junior Kalashala", description: "Film", category: "aha", year: "27-08-2024", image: "https://placehold.co/100x100?text=Prabuthwa+Junior+Kalashala" },
  { title: "Raayan", description: "Film", category: "amazon-prime", year: "23-08-2024", image: "https://placehold.co/100x100?text=Raayan" },
  { title: "Toofan", description: "Film", category: "amazon-prime", year: "23-08-2024", image: "https://placehold.co/100x100?text=Toofan" },
  { title: "Kalki 2898 AD", description: "Film", category: "amazon-prime", year: "22-08-2024", image: "https://placehold.co/100x100?text=Kalki+2898+AD" },
  { title: "Kaalarathri", description: "Film", category: "aha", year: "17-08-2024", image: "https://placehold.co/100x100?text=Kaalarathri" },
  { title: "Veeranjaneyulu Viharayathra", description: "Film", category: "etv-win", year: "14-08-2024", image: "https://placehold.co/100x100?text=Veeranjaneyulu+Viharayathra" },
  { title: "Darling", description: "Film", category: "disney-hotstar", year: "13-08-2024", image: "https://placehold.co/100x100?text=Darling" },
  { title: "Blink (Telugu)", description: "Film", category: "amazon-prime", year: "12-08-2024", image: "https://placehold.co/100x100?text=Blink" },
  { title: "Derick Abraham", description: "Film", category: "aha", year: "10-08-2024", image: "https://placehold.co/100x100?text=Derick+Abraham" },
  { title: "The Birthday Boy", description: "Film", category: "aha", year: "09-08-2024", image: "https://placehold.co/100x100?text=The+Birthday+Boy" },
  { title: "Bharateeyudu 2", description: "Film", category: "netflix", year: "09-08-2024", image: "https://placehold.co/100x100?text=Bharateeyudu+2" },
  { title: "D Block", description: "Film", category: "etv-win", year: "08-08-2024", image: "https://placehold.co/100x100?text=D+Block" },
  { title: "Theppa Samudram", description: "Film", category: "aha", year: "03-08-2024", image: "https://placehold.co/100x100?text=Theppa+Samudram" },
  { title: "Brinda", description: "Series", category: "sony-liv", year: "02-08-2024", image: "https://placehold.co/100x100?text=Brinda" },
  { title: "Satyabhama", description: "Film", category: "etv-win", year: "02-08-2024", image: "https://placehold.co/100x100?text=Satyabhama" },
  { title: "Rakshana", description: "Film", category: "aha", year: "01-08-2024", image: "https://placehold.co/100x100?text=Rakshana" },
  { title: "Bharathanatyam", description: "Film", category: "aha", year: "27-07-2024", image: "https://placehold.co/100x100?text=Bharathanatyam" },
  { title: "Yevam", description: "Film", category: "aha", year: "25-07-2024", image: "https://placehold.co/100x100?text=Yevam" },
  { title: "Kho Kho", description: "Film", category: "etv-win", year: "25-07-2024", image: "https://placehold.co/100x100?text=Kho+Kho" },
  { title: "Raju Yadav", description: "Film", category: "aha", year: "24-07-2024", image: "https://placehold.co/100x100?text=Raju+Yadav" },
  { title: "Aadujeevitham (Telugu)", description: "Film", category: "netflix", year: "19-07-2024", image: "https://placehold.co/100x100?text=Aadujeevitham" },
  { title: "Hot Spot (Telugu)", description: "Film", category: "netflix", year: "17-07-2024", image: "https://placehold.co/100x100?text=Hot+Spot" },
  { title: "Harom Hara", description: "Film", category: "aha", year: "16-07-2024", image: "https://placehold.co/100x100?text=Harom+Hara" },
  { title: "Music Shop Murthy", description: "Film", category: "etv-win", year: "16-07-2024", image: "https://placehold.co/100x100?text=Music+Shop+Murthy" },
  { title: "Jilebi", description: "Film", category: "aha", year: "13-07-2024", image: "https://placehold.co/100x100?text=Jilebi" },
  { title: "Maharaja (Telugu)", description: "Film", category: "netflix", year: "12-07-2024", image: "https://placehold.co/100x100?text=Maharaja" },
  { title: "Plot", description: "Film", category: "etv-win", year: "11-07-2024", image: "https://placehold.co/100x100?text=Plot" },
  { title: "Hit List", description: "Film", category: "amazon-prime", year: "09-07-2024", image: "https://placehold.co/100x100?text=Hit+List" },
  { title: "Malayalee From India (Telugu)", description: "Film", category: "sony-liv", year: "05-07-2024", image: "https://placehold.co/100x100?text=Malayalee+From+India" },
  { title: "Aarambham", description: "Film", category: "amazon-prime", year: "05-07-2024", image: "https://placehold.co/100x100?text=Aarambham" },
  { title: "Market Mahalakshmi", description: "Film", category: "aha", year: "04-07-2024", image: "https://placehold.co/100x100?text=Market+Mahalakshmi" },
  { title: "Aham Reboot", description: "Film", category: "aha", year: "01-07-2024", image: "https://placehold.co/100x100?text=Aham+Reboot" },
  { title: "Bhaje Vaayu Vegam", description: "Film", category: "netflix", year: "28-06-2024", image: "https://placehold.co/100x100?text=Bhaje+Vaayu+Vegam" },
  { title: "Satyabhama", description: "Film", category: "amazon-prime", year: "28-06-2024", image: "https://placehold.co/100x100?text=Satyabhama" },
  { title: "Love Mouli", description: "Film", category: "aha", year: "28-06-2024", image: "https://placehold.co/100x100?text=Love+Mouli" },
  { title: "Baak", description: "Film", category: "disney-hotstar", year: "21-06-2024", image: "https://placehold.co/100x100?text=Baak" },
  { title: "Gam Gam Ganesha", description: "Film", category: "amazon-prime", year: "20-06-2024", image: "https://placehold.co/100x100?text=Gam+Gam+Ganesha" },
  { title: "Gangs Of Godavari", description: "Film", category: "netflix", year: "14-06-2024", image: "https://placehold.co/100x100?text=Gangs+Of+Godavari" },
  { title: "Love Me If You Dare", description: "Film", category: "amazon-prime", year: "14-06-2024", image: "https://placehold.co/100x100?text=Love+Me+If+You+Dare" },
  { title: "Dear Nanna", description: "Film", category: "aha", year: "14-06-2024", image: "https://placehold.co/100x100?text=Dear+Nanna" },
  { title: "Yakshini", description: "Film", category: "disney-hotstar", year: "14-06-2024", image: "https://placehold.co/100x100?text=Yakshini" },
  { title: "Rush", description: "Film", category: "etv-win", year: "13-06-2024", image: "https://placehold.co/100x100?text=Rush" },
  { title: "Paarijatha Parvam", description: "Film", category: "aha", year: "12-06-2024", image: "https://placehold.co/100x100?text=Paarijatha+Parvam" },
  { title: "Ground", description: "Film", category: "amazon-prime", year: "10-06-2024", image: "https://placehold.co/100x100?text=Ground" },
  { title: "105 Minuttess", description: "Film", category: "aha", year: "07-06-2024", image: "https://placehold.co/100x100?text=105+Minuttess" },
  { title: "Tenant", description: "Film", category: "amazon-prime", year: "07-06-2024", image: "https://placehold.co/100x100?text=Tenant" },
  { title: "Kalki (Telugu)", description: "Film", category: "etv-win", year: "07-06-2024", image: "https://placehold.co/100x100?text=Kalki" },
  { title: "Miral", description: "Film", category: "aha", year: "07-06-2024", image: "https://placehold.co/100x100?text=Miral" },
  { title: "Aa Okkati Adakku", description: "Film", category: "amazon-prime", year: "31-05-2024", image: "https://placehold.co/100x100?text=Aa+Okkati+Adakku" },
  { title: "Project Z", description: "Film", category: "aha", year: "31-05-2024", image: "https://placehold.co/100x100?text=Project+Z" },
  { title: "Raamanna Youth", description: "Film", category: "etv-win", year: "30-05-2024", image: "https://placehold.co/100x100?text=Raamanna+Youth" },
  { title: "Keechurallu", description: "Film", category: "etv-win", year: "30-05-2024", image: "https://placehold.co/100x100?text=Keechurallu" },
  { title: "Sriranga Neethulu", description: "Film", category: "aha", year: "29-05-2024", image: "https://placehold.co/100x100?text=Sriranga+Neethulu" },
  { title: "Prasanna Vadanam", description: "Film", category: "aha", year: "24-05-2024", image: "https://placehold.co/100x100?text=Prasanna+Vadanam" },
  { title: "Aarambham", description: "Film", category: "etv-win", year: "23-05-2024", image: "https://placehold.co/100x100?text=Aarambham" },
  { title: "Rathnam (Telugu)", description: "Film", category: "amazon-prime", year: "23-05-2024", image: "https://placehold.co/100x100?text=Rathnam" },
  { title: "Kaliyugam Pattanamlo", description: "Film", category: "amazon-prime", year: "23-05-2024", image: "https://placehold.co/100x100?text=Kaliyugam+Pattanamlo" },
  { title: "Sharathulu Varthisthai", description: "Film", category: "aha", year: "18-05-2024", image: "https://placehold.co/100x100?text=Sharathulu+Varthisthai" },
  { title: "Krishnamma", description: "Film", category: "amazon-prime", year: "17-05-2024", image: "https://placehold.co/100x100?text=Krishnamma" },
  { title: "Vidya Vasula Aham", description: "Film", category: "aha", year: "17-05-2024", image: "https://placehold.co/100x100?text=Vidya+Vasula+Aham" },
  { title: "Praveen IPS", description: "Film", category: "hungama-play", year: "12-05-2024", image: "https://placehold.co/100x100?text=Praveen+IPS" },
  { title: "Love Guru", description: "Film", category: "amazon-prime", year: "11-05-2024", image: "https://placehold.co/100x100?text=Love+Guru" },
  { title: "S.I.T", description: "Film", category: "zee5", year: "10-05-2024", image: "https://placehold.co/100x100?text=S.I.T" },
  { title: "Chitram Choodara", description: "Film", category: "etv-win", year: "09-05-2024", image: "https://placehold.co/100x100?text=Chitram+Choodara" },
  { title: "Parthu", description: "Film", category: "etv-win", year: "09-05-2024", image: "https://placehold.co/100x100?text=Parthu" },
  { title: "Geethanjali Malli Vachindi", description: "Film", category: "aha", year: "08-05-2024", image: "https://placehold.co/100x100?text=Geethanjali+Malli+Vachindi" },
  { title: "Manjummel Boys (Telugu)", description: "Film", category: "disney-hotstar", year: "05-05-2024", image: "https://placehold.co/100x100?text=Manjummel+Boys" },
  { title: "Happy Ending", description: "Film", category: "aha", year: "03-05-2024", image: "https://placehold.co/100x100?text=Happy+Ending" },
  { title: "Siddharth Roy", description: "Film", category: "aha", year: "03-05-2024", image: "https://placehold.co/100x100?text=Siddharth+Roy" },
  { title: "Lineman", description: "Film", category: "amazon-prime", year: "03-05-2024", image: "https://placehold.co/100x100?text=Lineman" },
  { title: "Asura Guru", description: "Film", category: "aha", year: "03-05-2024", image: "https://placehold.co/100x100?text=Asura+Guru" },
  { title: "Pranaya Vilasam", description: "Film", category: "etv-win", year: "02-05-2024", image: "https://placehold.co/100x100?text=Pranaya+Vilasam" },
  { title: "Family Star", description: "Film", category: "amazon-prime", year: "26-04-2024", image: "https://placehold.co/100x100?text=Family+Star" },
  { title: "Tillu Square", description: "Film", category: "netflix", year: "26-04-2024", image: "https://placehold.co/100x100?text=Tillu+Square" },
  { title: "Chunduru Police Station", description: "Film", category: "aha", year: "26-04-2024", image: "https://placehold.co/100x100?text=Chunduru+Police+Station" },
  { title: "Bhimaa", description: "Film", category: "disney-hotstar", year: "25-04-2024", image: "https://placehold.co/100x100?text=Bhimaa" },
  { title: "My Dear Donga", description: "Film", category: "aha", year: "19-04-2024", image: "https://placehold.co/100x100?text=My+Dear+Donga" },
  { title: "Saagu", description: "Film", category: "aha", year: "14-04-2024", image: "https://placehold.co/100x100?text=Saagu" },
  { title: "Om Bheem Bush", description: "Film", category: "amazon-prime", year: "12-04-2024", image: "https://placehold.co/100x100?text=Om+Bheem+Bush" },
  { title: "Gaami", description: "Film", category: "zee5", year: "12-04-2024", image: "https://placehold.co/100x100?text=Gaami" },
  { title: "Yatra 2", description: "Film", category: "amazon-prime", year: "12-04-2024", image: "https://placehold.co/100x100?text=Yatra+2" },
  { title: "Premalu (Telugu)", description: "Film", category: "aha", year: "12-04-2024", image: "https://placehold.co/100x100?text=Premalu" },
  { title: "Sharma And Ambani", description: "Film", category: "etv-win", year: "11-04-2024", image: "https://placehold.co/100x100?text=Sharma+And+Ambani" },
  { title: "Kajal Karthika", description: "Film", category: "aha", year: "09-04-2024", image: "https://placehold.co/100x100?text=Kajal+Karthika" },
  { title: "Chaari 111", description: "Film", category: "amazon-prime", year: "05-04-2024", image: "https://placehold.co/100x100?text=Chaari+111" },
];

export const items2023: Item[] = [
  { title: "Show C", description: "Romantic comedy", category: "jiohotstar", year: "12-02-2023", image: "https://placehold.co/100x100?text=Show+C" },
  { title: "Show I", description: "Reality TV", category: "jiohotstar", year: "18-05-2023", image: "https://placehold.co/100x100?text=Show+I" },
  { title: "Show O", description: "Comedy show", category: "jiohotstar", year: "25-08-2023", image: "https://placehold.co/100x100?text=Show+O" },
];

export const items2022: Item[] = [
  { title: "Film D", description: "Sci-fi adventure", category: "aha", year: "30-01-2022", image: "https://placehold.co/100x100?text=Film+D" },
  { title: "Film J", description: "Horror movie", category: "aha", year: "14-04-2022", image: "https://placehold.co/100x100?text=Film+J" },
  { title: "Film P", description: "Action thriller", category: "aha", year: "22-07-2022", image: "https://placehold.co/100x100?text=Film+P" },
];

export const items2021: Item[] = [
  { title: "Drama E", description: "Historical drama", category: "sun-nxt", year: "10-03-2021", image: "https://placehold.co/100x100?text=Drama+E" },
  { title: "Drama K", description: "Social drama", category: "sun-nxt", year: "19-06-2021", image: "https://placehold.co/100x100?text=Drama+K" },
  { title: "Drama Q", description: "Biographical drama", category: "sun-nxt", year: "28-09-2021", image: "https://placehold.co/100x100?text=Drama+Q" },
];

export const items2020: Item[] = [
  { title: "Thriller F", description: "Psychological thriller", category: "sony-liv", year: "05-02-2020", image: "https://placehold.co/100x100?text=Thriller+F" },
  { title: "Thriller L", description: "Mystery thriller", category: "sony-liv", year: "17-05-2020", image: "https://placehold.co/100x100?text=Thriller+L" },
  { title: "Thriller R", description: "Crime thriller", category: "sony-liv", year: "29-08-2020", image: "https://placehold.co/100x100?text=Thriller+R" },
];